#!/usr/bin/env python3
"""Generate docs/function-map.md from data/names.json + data/gnames.json (+ work/db.pkl for stats).

The JSON files are the curated source of truth: every entry carries a confidence and the
evidence behind the name. Re-run after adding names:  python3 genmap.py > ../../docs/function-map.md
"""
import json
import os
import pickle
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
names = json.load(open(os.path.join(HERE, 'data', 'names.json')))
gnames = json.load(open(os.path.join(HERE, 'data', 'gnames.json')))
try:
    D = pickle.load(open(os.path.join(HERE, 'work', 'db.pkl'), 'rb'))
    NFUNCS = len(D['funcs'])
except Exception:
    NFUNCS = None

# Approximate module boundaries (VA, object 1 base 0x10000).  Derived from string anchors and
# call-graph clustering, NOT from symbols: treat boundaries as +-a few hundred bytes.
MODULES = [
    (0x10000, 'App startup / config / HMI sound glue'),
    (0x11500, 'Artic (articulated vehicle parts)'),
    (0x12d80, 'Frame clock'),
    (0x13000, 'Collide (collision cubes/faces)'),
    (0x1695d, 'Com (serial / modem / IPX)'),
    (0x18034, 'Draw3D (3D pipeline, materials, polygons)'),
    (0x1e2f3, 'Texture / sprite lookup'),
    (0x1e6b8, 'Slot servers (misc)'),
    (0x1eb3c, 'DOS file layer + RES archive access'),
    (0x1f582, 'Slot servers (misc)'),
    (0x1fc14, 'Input (keyboard / mouse / joystick)'),
    (0x20a86, 'DOS runtime glue (exit, Windows check, key recorder)'),
    (0x21100, 'Maths (trig, sqrt, vectors, matrices)'),
    (0x24100, 'Random + Res manager'),
    (0x25a00, 'Shapes (.SHP)'),
    (0x26750, 'Slots (entity system)'),
    (0x28680, 'String tables + Timer'),
    (0x29b00, 'Event + Text engine'),
    (0x2c000, 'Video + blitters / rasterisers'),
    (0x33100, 'LBM writer / VESA / text-map tables'),
    (0x33f00, 'Track'),
    (0x3f200, 'Track decor / driver faces'),
    (0x41800, 'Front-end (garage, menus, link screens)'),
    (0x4a086, 'Debug log / drones / sound FX'),
    (0x4c000, 'Weapons UI / garage'),
    (0x4f2c0, 'Race effects (bang, bonus, damage)'),
    (0x5047c, 'Race slot (vehicle) control + physics'),
    (0x53000, 'Save / load game'),
    (0x55750, 'Game main / mode dispatch'),
    (0x56600, 'Results / credits'),
    (0x57800, 'Intro scripts'),
    (0x586f2, 'DoGame3D (race)'),
    (0x59ae3, 'Race UI / link waiting / results'),
    (0x5b8bf, 'Sprite effects / palette fades'),
    (0x5bb6e, 'Protection trampoline / replay'),
    (0x5c0f9, 'Weapons'),
    (0x5d8b2, 'Watcom C runtime (printf, strcmp ...)'),
    (0x63978, 'Watcom startup + DOS/4GW glue'),
    (0x64000, 'HMI SOS runtime / DPMI glue'),
]


def module(addr):
    m = MODULES[0][1]
    for start, name in MODULES:
        if addr >= start:
            m = name
        else:
            break
    return m


def esc(s):
    return s.replace('|', '\\|').replace('\n', ' ')


def name_source(name, ev):
    return 'original' if ("'" + name) in ev else 'inferred'


out = []
P = out.append
P('# Function map\n')
P('Generated by `tools/re/genmap.py` from `tools/re/data/names.json` and `gnames.json`. '
  'Do not edit this file by hand — edit the JSON (via `tools/re/nm.py` or a bulk script) and regenerate.\n')
P('**Addresses** are virtual addresses in the original image: LE object 1 (code) is based at `0x10000`, '
  'object 3 (data/stack) at `0x80000`. File offset of a code VA = `0x4D854 + (VA - 0x10000)` for the '
  'page-aligned image bytes (see `executable-analysis.md` §2).\n')
P('## Conventions\n')
P('| Confidence | Meaning |')
P('|---|---|')
P('| **high** | The name (or exact role) is established by an original string embedded in the function '
  '(the game\'s own error messages name their functions), or by a structural match that was validated '
  'against real data / observed behaviour. |')
P('| **medium** | Strong behavioural evidence (constants, call pattern, data flow, direct callers) but no original name; the name is descriptive and invented by us. |')
P('| **low** | Plausible inference; do not build on it without re-verifying. |\n')
P('| Name source | Meaning |')
P('|---|---|')
P('| original | The identifier appears in the executable as part of an error message (the programmers\' own naming). |')
P('| inferred | Name chosen by us from behaviour. |\n')
tot = len(names)
c = {'high': 0, 'medium': 0, 'low': 0}
for v in names.values():
    c[v['conf']] = c.get(v['conf'], 0) + 1
P('## Statistics\n')
if NFUNCS:
    P('* Functions recovered by static analysis: **%d** (about 78%% of the 382,148-byte code object decoded as instructions; the rest is data and some undiscovered code).' % NFUNCS)
P('* Functions named in this map: **%d** (high %d, medium %d, low %d).' % (tot, c.get('high', 0), c.get('medium', 0), c.get('low', 0)))
P('* Global/data labels: **%d**.\n' % len(gnames))

P('## Named functions (by address)\n')
P('| VA | Name | Module (approx.) | Conf. | Source | Evidence |')
P('|---|---|---|---|---|---|')
for k in sorted(names, key=lambda x: int(x, 16)):
    v = names[k]
    a = int(k, 16)
    P('| `0x%05X` | `%s` | %s | %s | %s | %s |' % (a, v['name'], module(a), v['conf'], name_source(v['name'], v['evidence']), esc(v['evidence'])))

P('\n## Global variables and tables\n')
P('| VA | Label | Note |')
P('|---|---|---|')
for k in sorted(gnames, key=lambda x: int(x, 16)):
    v = gnames[k]
    P('| `0x%05X` | `%s` | %s |' % (int(k, 16), v['name'], esc(v.get('note', ''))))

P('\n## Notable functions that are intentionally left unnamed\n')
P('These were profiled but their role is not yet established well enough to name. They are listed so the next phase knows where the renderer hot spots are.\n')
P('| VA | Size (insns) | Observation | Confidence |')
P('|---|---|---|---|')
for a, n, obs, conf in [
    (0x2DE6D, 2288, 'Gigantic unrolled routine, 910 references into a work area at 0x30xxx and the text-map table pointer [0x33310]; contains IDIV by edge slope and span-length dispatch (<0x14, >=0x28 …). Almost certainly the perspective/affine **textured polygon scanline** core, called from 0x2DC2F and 0x308E2/0x30CB3.', 'low'),
    (0x2DC2F, 160, 'Wrapper that selects scanline routine; calls 0x2DE6D.', 'low'),
    (0x2D614, 134, 'Video primitive (flat span / rect) in the 0x2Dxxx cluster.', 'low'),
    (0x2CDBE, 96, 'Video primitive with 10 callers (sprite/rect blit family 0x2C7B7..0x2CEA0).', 'low'),
    (0x1AE47, 189, 'Draw3D polygon submit; 11 callers, calls 0x2CCD0/0x2CDBE/0x2D1CF/0x2D3EA/0x2DC2F (video rasterisers). Likely the **polygon dispatcher** (flat / Gouraud / textured).', 'low'),
    (0x1BA7D, 166, 'Polygon clipper/edge walker: calls edge routines 0x1B098/0x1B14B/0x1CCE9/0x1CE38.', 'low'),
    (0x19ACC, 174, 'Draw3D polygon set-up with 5 indirect branches (shading-mode jump).', 'low'),
    (0x1D039, 103, '16 callers; clip/outcode helper.', 'low'),
    (0x1DCF7, 51, 'Point transform loop used by ShapeDraw (callbacks 0x26295/0x262D8 do the 3x3 matrix multiply, SAR 14, then translate).', 'medium'),
    (0x1E240, 26, 'Polygon-to-Draw3D hand-off called through 0x26020 from ShapeDraw.', 'low'),
    (0x1F7A0, 204, 'Large slot-server (random velocities, ResAlloc, ShapeScale 0x26026): debris/fragment spawner.', 'low'),
    (0x4429D, 139, 'Per-frame sprite/text overlay drawing (HUD).', 'low'),
]:
    P('| `0x%05X` | %d | %s | %s |' % (a, n, obs, conf))

sys.stdout.write('\n'.join(out) + '\n')
